version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # 一旦H2-db
      KC_DB: dev-file
      KC_DB_URL_PATH: /opt/keycloak/data/keycloakdb
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
      - keycloak_conf:/opt/keycloak/conf
    command: start-dev

volumes:
  keycloak_data:
    driver: local
  keycloak_conf:
    driver: local
