version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: vpn
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devuser
    volumes:
      - postgres_data:/var/lib/postgresql/data
    network_mode: host

volumes:
  postgres_data:
